/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#313030",
        "on-secondary-fixed": "#201a1a",
        "on-tertiary-container": "#730a1b",
        "on-primary": "#003914",
        "primary-container": "#1db954",
        "tertiary-container": "#ff767b",
        "surface-container": "#201f1f",
        "inverse-primary": "#006e2d",
        "surface-container-high": "#2a2a2a",
        "surface-container-lowest": "#0e0e0e",
        "inverse-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "on-tertiary-fixed": "#400009",
        "on-error": "#690005",
        "on-secondary-container": "#bdb3b2",
        "on-surface-variant": "#bccbb9",
        error: "#ffb4ab",
        primary: "#53e076",
        "surface-container-highest": "#353534",
        secondary: "#cfc4c4",
        "surface-dim": "#131313",
        outline: "#869585",
        "secondary-container": "#4c4545",
        "primary-fixed": "#72fe8f",
        "on-primary-fixed-variant": "#005320",
        "tertiary-fixed-dim": "#ffb3b3",
        "on-tertiary-fixed-variant": "#881d28",
        "on-primary-container": "#004118",
        tertiary: "#ffb3b3",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1c1b1b",
        "secondary-fixed": "#ebe0df",
        "surface-tint": "#53e076",
        "on-surface": "#e5e2e1",
        "on-primary-fixed": "#002108",
        "outline-variant": "#3d4a3d",
        "tertiary-fixed": "#ffdad9",
        "on-secondary": "#352f2f",
        "primary-fixed-dim": "#53e076",
        "surface-bright": "#393939",
        "on-secondary-fixed-variant": "#4c4545",
        background: "#131313",
        "error-container": "#93000a",
        "on-tertiary": "#680114",
        surface: "#131313",
        "secondary-fixed-dim": "#cfc4c4",
        "surface-variant": "#353534",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        xs: "4px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "16px",
        "container-margin": "24px",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-sm": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.04em", fontWeight: "900" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
      keyframes: {
        "pulse-ring": {
          "0%, 100%": { transform: "scale(0.95)", opacity: "0.8" },
          "50%": { transform: "scale(1.05)", opacity: "0.4" },
        },
        scan: {
          "0%, 100%": { top: "0%" },
          "50%": { top: "100%" },
        },
      },
      animation: {
        "pulse-slow": "pulse-ring 3s cubic-bezier(0.4,0,0.6,1) infinite",
        scan: "scan 4s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
